import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const getHeading = localFont({
  variable: "--font-heading",
  src: [
    {
      path: "../public/fonts/T star/T-StarPro-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/T star/T-StarPro-LightItalic.ttf",
      weight: "300",
      style: "italic",
    },
    {
      path: "../public/fonts/T star/T-StarPro-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/T star/T-StarPro-RegularItalic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/T star/T-StarPro-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/T star/T-StarPro-MediumItalic.ttf",
      weight: "500",
      style: "italic",
    },
    {
      path: "../public/fonts/T star/T-StarPro-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/T star/T-StarPro-BoldItalic.ttf",
      weight: "700",
      style: "italic",
    },
    {
      path: "../public/fonts/T star/T-StarPro-Heavy.ttf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/fonts/T star/T-StarPro-HeavyItalic.ttf",
      weight: "900",
      style: "italic",
    },
  ],
});

const getBody = Poppins({
  variable: "--font-body",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${getHeading.variable} ${getBody.variable} flex min-h-screen flex-col antialiased`}
      >
        <div className="flex-1">{children}</div>
      </body>
    </html>
  );
}
